<?php
include ("poo.php");

class Coche extends Vehiculo{

    private $categoria;

    function __construct($motor, $color, $ruedas,$categoria)
    {
        parent::__construct($motor, $color, $ruedas);
        $this->categoria=$categoria;

    }



    function girar()
    {
        parent::girar();
        echo " el coche";
    }

    function frenar()
    {
        parent::frenar(); // TODO: Change the autogenerated stub
    }

    function set_color($color)
    {
        parent::set_color($color); // TODO: Change the autogenerated stub
    }

    function set_motor($motor)
    {
        parent::set_motor($motor); // TODO: Change the autogenerated stub
    }


   function get_ruedas()
  {
      return parent::get_ruedas(); // TODO: Change the autogenerated stub
  }

  function get_categoria(){
        return $this->categoria;
  }

  function variasAcciones(){
        $this->arrancar();
      echo " el coche. También  ";
        $this->girar();
  }
}

class Moto extends Vehiculo{

}
class Caminon{

}

$mazda=new Coche(1900,"Azul",5,"SUV");
echo "<br/><br/>Archivo actual:<br/>";
$mazda->arrancar();
echo "<br/> $mazda->ruedas";
//echo "<br/>".$mazda->parent::get_ruedas();Fatal error: Uncaught Error: Class name must be a valid object or a string in C:\xampp\htdocs\phpstorm\phpstorm\repaso\coche_moto.php

echo "<br/>".$mazda->get_categoria();
//echo "<br/> $mazda->categoria"; Fatal error: Uncaught Error: Cannot access private property Coche::$categoria in C:\xampp\htdocs\phpstorm\phpstorm\repaso\coche_moto.php
echo "<br/>".Vehiculo::get_combustible();

$honda=new Moto(600,"Negro",2);
echo "<br/>";
echo $honda->color;
echo "<br/>";
echo $honda->ruedas;
echo "<br/>";
echo $honda->jamon;
echo "<br/>";
$honda->motor=800;
echo "<br/>";
echo $honda->motor;

$mazda->set_precio_base(15000);
$honda->set_precio_base(9500);
Vehiculo::descuentoGobierno();
echo "<br/>";
echo $mazda->precio_final();
echo "<br/>";
echo $honda->precio_final();
echo "<br/>";
$mazda->girar();
echo "<br/>";
$mazda->variasAcciones();


?>
